apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejsapp-config
  namespace: backend-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Apply after secrets and deployments
data:
  DB_HOST: mysql-headless-service.db-namespace
  DB_DATABASE: my_testing_db
  DB_PORT: "3306"
  ALLOWED_ORIGIN: http://front.localhost
  DB_CONNECTION: mysql
