apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-application
  namespace: argocd # Argo CD namespace
spec:
  project: default
  source:
    repoURL: https://github.com/utkarsh4321/devops-deployment-repo.git
    targetRevision: main # Or your branch
    path: eks/frontend # Path in Git containing ALL manifests (Deployment, ConfigMap, Secret)
    directory:
      recurse: true
  destination:
    # server: https://kubernetes.default.svc
    server: https://87435092CC6F491699AD2706A1771C44.gr7.ap-south-1.eks.amazonaws.com
    namespace: frontend-namespace # Target namespace in the cluster
  syncPolicy:
    automated:
      prune: true # Deletes old resources
      selfHeal: true # Auto-fixes drifts
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=true # Key for Secrets: Forces delete + recreate on immutable field changes
