apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store-applications
  namespace: argocd # Argo CD namespace
spec:
  project: default
  source:
    repoURL: https://github.com/utkarsh4321/devops-deployment-repo.git
    targetRevision: main # Or your branch
    path: eks/external-secret # Path in Git containing ALL manifests (Deployment, ConfigMap, Secret)
    # directory:
    #   recurse: true
  destination:
    server: https://4B9C00A51E382BC3C62E862277E12182.gr7.ap-south-1.eks.amazonaws.com
    namespace: default # Target namespace in the cluster
  syncPolicy:
    automated:
      prune: true # Deletes old resources
      selfHeal: true # Auto-fixes drifts
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=true # Key for Secrets: Forces delete + recreate on immutable field changes
      - ApplyOutOfSyncOnly=true
