kind: ConfigMap
apiVersion: v1
metadata:
  name: reactjsapp-config
  namespace: frontend-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Apply after db and backend
data:
  VITE_API_URL: http://api.localhost
