apiVersion: v1
data:
  DATABASE_NAME: my_testing_db
  # PMA_HOST: mysql-service
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-config
  namespace: db-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-3" # Apply first
    argocd.argoproj.io/hook: Sync
    # reloader.stakater.com/auto: "true"
