apiVersion: v1
data:
  DATABASE_NAME: my_testing_db
  # PMA_HOST: mysql-service
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-config
  namespace: db-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Apply first
